### ISSUE TITLE
Tutorial not working.

### ISSUE THREAD

**Issue by friendRU** [vzhukovskii/che-bookmark-plugin#1]
Hello, your tutorial does not work with the version of che 4.2.0-RC1-SNAPSHOT. In this version some paths and classes are not created, such as
_org.eclipse.che.ide.api.resources.Resource;
org.eclipse.che.ide.api.workspace.Workspace;_
etc.

In later versions of some of the problems disappear, but they have changed the API and there is no class _org.eclipse.che.ide.api.workspace.Workspace;_

Maven project is not going to even start.

**Question:** which version(s) use to get everything working well?

Logs assembly deflated project:

**mvn clean install**

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Che Plugin :: Bookmarks :: Parent 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ che-bookmark-plugin ---
[INFO] Deleting C:\temp\che-bookmark-plugin-master\target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:parse-version (parse-version) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ che-bookmark-plugin ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\temp\che-bookmark-plugin-master
[INFO] Storing buildNumber: no_revision at timestamp: 20160919
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: 'git' is not recognized as an internal or external command,
operable program or batch file.

[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\temp\che-bookmark-plugin-master
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java-version) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven-version) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (distribution-management-used) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (no-distribution-management-at-all) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (dependency) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (ban-bad-dependencies) @ che-bookmark-plugin ---
[INFO] 
[INFO] --- maven-sortpom-plugin:2.3.0:verify (default) @ che-bookmark-plugin ---
[INFO] Verifying file C:\temp\che-bookmark-plugin-master\pom.xml
[INFO] 
[INFO] --- license-maven-plugin:2.10:check (check-headers) @ che-bookmark-plugin ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ che-bookmark-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 16 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ che-bookmark-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to C:\temp\che-bookmark-plugin-master\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.687 s
[INFO] Finished at: 2016-09-19T12:44:56+04:00
[INFO] Final Memory: 38M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project che-bookmark-plugin: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by vzhukovskii** [comment]
Thanks for the feedback, I'll take a look on it, ASAP. This repository has to be updated to use the new codebase, cause there were a lot changes during these month.

**Comment by friendRU** [comment]
May be you tell how can to change Workspace.class already?(

**Comment by friendRU** [comment]
Vladislav, please repair this project.

**Comment by vzhukovskii** [comment]
@friendRU I've updated plugin and added assembly to build Che with integrated plugin, so now there is no need to build plugin and then Che, you can build whole project in the repository and run Che with the plugin included.

**Comment by vzhukovskii** [comment]
Readme I'll update soon.

**Comment by friendRU** [comment]
Nice) Thank you)
