### ISSUE TITLE
Will it work on java 8 and 11

### ISSUE THREAD

**Issue by Rahith-RR** [vzhukovskii/che-bookmark-plugin#3]
It says in readme "As the Eclipse Che uses GWT library 2.7, client side can be written using only java 7".
But, will it work on all versions after java 7?

**Comment by vzhukovskii** [comment]
It should work, AFAIK with java 8, but with one condition - client side should have java 7 syntax. Then it will work. For java 11, I'm not sure. GWT 2.7 officially supports java 7.

**Comment by Rahith-RR** [comment]
Thank you for your reply
