### ISSUE TITLE
Facing issue while building using "mvn clean install". Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT  Please help to run the project

### ISSUE THREAD

**Issue by Rahith-RR** [vzhukovskii/che-bookmark-plugin#4]
**I am using online IDE of eclipse che.
Below is the issue that i am facing while trying to build the project:-**

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT: Could not transfer artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.0.0-M5-SNAPSHOT from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): Transfer failed for https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 16, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT (/projects/che-bookmark-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT: Could not transfer artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.0.0-M5-SNAPSHOT from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): Transfer failed for https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 16, column 13: Connect to maven.codenvycorp.com:443 [maven.codenvycorp.com/54.235.115.153] failed: Connection timed out (Connection timed out) -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Below is the java and maven configurations of Online che IDE:**

bash-5.0 /projects/che-bookmark-plugin $ **java -version**
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)

bash-5.0 /projects/che-bookmark-plugin $ **mvn -version**
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Oracle Corporation, runtime: /usr/local/openjdk-11
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.21.3.el7.x86_64", arch: "amd64", family: "unix"

**Comment by vzhukovskii** [comment]
Hi @Rahith-RR, see the comment on separate issue about this thing: https://github.com/vzhukovskii/che-gradle-plugin/issues/1#issuecomment-656577643. This repository and https://github.com/vzhukovskii/che-gradle-plugin are no longer supported as Che 5. In future, please, create issue, related to Eclipse Che in https://github.com/eclipse/che/issues/new/choose, it is easier to track such questions in main repo.

**Comment by Rahith-RR** [comment]
Thanks @vzhukovskii for the info.
